image: s2shape/s2shape-test-harness:latest

stages:
  - build
  - test

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

variables:
  SNOWFLAKE_ACCOUNT: burilovmv
  SNOWFLAKE_REGION: us-west1
  SNOWFLAKE_DB: testdb
  SNOWFLAKE_USER: user
  SNOWFLAKE_PASS: a43Nj%HT890v
  SNOWFLAKE_CONNECT: ACCOUNT=$SNOWFLAKE_ACCOUNT;HOST=$SNOWFLAKE_ACCOUNT.$SNOWFLAKE_REGION.snowflakecomputing.com;DB=$SNOWFLAKE_DB;USER=$SNOWFLAKE_USER,PASSWORD=$SNOWFLAKE_PASS

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/SnowflakeSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init SnowflakeSupplyCollector "$SNOWFLAKE_CONNECT"
    - dotnet SupplyCollectorDataLoader.dll -xunit SnowflakeSupplyCollector "$SNOWFLAKE_CONNECT"
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/SnowflakeSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init SnowflakeSupplyCollector "$SNOWFLAKE_CONNECT"
    - dotnet SupplyCollectorDataLoader.dll -xunit SnowflakeSupplyCollector "$SNOWFLAKE_CONNECT"
    - dotnet SupplyCollectorDataLoader.dll -samples SnowflakeSupplyCollector "$SNOWFLAKE_CONNECT" TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/SnowflakeSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness -connect "$SNOWFLAKE_CONNECT" test_harness.config
